name: Next.js CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v4

    - name: ⚙️ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
      env:
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    - name: 📦 Install Dependencies
      run: npm install

    - name: 🗄️ Generate Prisma Client
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      run: npx prisma generate

    - name: 🏗️ Build Next.js App
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }} 
      run: npm run build

    - name: 🚀 Upload & Replace Otomatis via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ./
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.next/cache/**
          .env
          server.js
          next.config.mjs
